export const Messages = {
  EMAIL_ALREADY_IN_USE: "Email is already in use, please login!",
  USER_REGISTER_SUCCESS: "User registered successfully!",
  INVALID_CREDENTIALS: "Invalid Credentials",
  EVENT_REMINDER: "Event reminder scheduled successfully",
  BOOKING_CONFIRMATION_EMAIL: "Event booking confirmation email sent",
  BOOKING_CANCELLATION_EMAIL: "Booking cancellation email sent",
  LOGIN_WORKING: "Login is working",
  REGISTRATION_EMAIL_SENT: "Registration email sent",
  LOGOUT_SUCCESS: "Logged out successfully.",
  NOT_PERMISSION_TO_ACCESS:
    "You do not have permission to access this resource",
  UNAUTHORIZED_ACCESS: "Unauthorized Access Attempt!",
  INVALID_TOKEN: "Invalid or expired token.",
  ACCOUNT_INACTIVE: "User account is inactive.",
  ACCESS_DENIED: "Access denied: Admins only",
  HELLO_WORLD: "Hello World!",
  ERROR: {
    INTERNAL_SERVER_ERROR: "Internal Server Error",
  },
  AUTH: {
    COOKIE_DELETED_SUCCESS: "Successfully logged out, token cookie deleted",
  },

  DASHBOARD: "Admin dashboard",
  DATA_IN_DASHBOARD: "Data fetched successfully in dashboard.",
  LOGGED_SUCCESS: "Logged in successfully",
  NO_TOKEN: "No token provided",
  INVALID_EXPIRED_TOKEN: "Invalid or expired token",
  USER_NOT_FOUND: "User not found",
  LOG_OUT: "Log out the user",
  LOG_IN: "Log in to use the API's",
  SIGN_UP: "Sign up as to play with API's.",
  SIGNUP_SUCCESS: "Signup successfully",
  PASSWORD_CONDITION: "Password should be at least 6 characters long",
  PASSWORD_REQUIRED: "Password is required",
  EMAIL_REQUIRED: "Email is required",
  VALID_EMAIL: "Email must be a valid",
  GET_PROFILE: "Get profile.",
  EMAIL_SCHEDULE_SUCCESS: "Email scheduled successfully",
  SENDING_CONFIRMATION_EMAIL: "Sending confirmation mail.",
  SENDING_MAIL: "Sending mail.",
  SENDING_REMINDER_MAIL: "Sending reminder mail for respective event",
  SENDING_CANCELLATION_MAIL: "Sending email for cancelling the event.",
};

export const auth = {
  CORS_LINK: "http://[::1]:3000",
  MAX_AGE: "3h",
  ACCESS_TOKEN: "access_token",
  STATUS: {
    OK: 200,
  },
  SERVER_RUNNING_ON_URL: "Server is running on URL: ",
};
