export const Messages = {
  CHECK_UPCOMING_EVENTS: "Checking for the upcoming events...",
  EVENT_REMINDER: "Event Reminder",
  FAIL_EVENT_REMINDER: "Failed to send event reminder",
  REGISTRATION_SUCCESS: "Registration successful email",
  REGISTERING_THANKS:
    "Thank you for registering. We are excited to have you on board.",
  EVENT_BOOKING_CONFIRMATION: "Event Booking Confirmation Email",
  BOOKING_CANCELLATION: "Booking cancellation",
  SMTP_VERIFICATION_FAILED: "SMTP Verification Failed:",
  SMTP_SERVER_READY: "SMTP Server is Ready",
  EVENT_NOT_FOUND: "Event not found",
  EVENT_IMAGE_UPDATED: "Event image updated successfully",
  EVENT_DATA_UPDATED: "Event data updated successfully",
  ALREADY_REGISTERED_USER: "User is already registered for this event.",
  FILE_FORMAT: "Invalid file format. Please upload JPEG or PNG images only.",
  EMAIL: "Email already exists.",
  FAIL_TO_SEND_EMAIL_CANCELLATION:
    "Failed to send booking cancellation email to",
  FAIL_TO_SEND_EMAIL_CONFIRMATION:
    "Failed to send booking confirmation email to ",
  BOOKING_CANCELLATION_EMAIL: "Booking cancellation email sent to",
  BOOKING_IS_CANCELLED: "Your booking is cancelled for the event",
  BOOKING_IS_CONFIRMED: "Your booking is cancelled for the event",
  FAILED_TO_SENT_EMAIL: "Failed to send email to ",
  FAILED_TO_SENT_REGISTRATION_EMAIL: "Failed to send registration email to ",
  EVENT_BOOKING_CONFIRMATION_SENDTO: "Event booking confirmation sent to",
  EVENT_NOT_FOUND_ID: "Event not found with ID",
  NO_ATTENDEES_FOUND_FOR_EVENT: "No attendees found for event ",
  REMINDER_YOUR_EVENT: "Reminder: Your event ",
  IS_SCHEDULED_ON: " is scheduled on",
  EVENT_REMINDER_SEND_TO: "Event reminder sent to",
  ATTENDEES_FOR: "attendees for",
  REGISTRATION_EMAIL_SEND_TO: "Registration email send to",
  EMAIL_SEND_TO: "Email send to ",
  EMAIL_SCHEDULED_TO: "Email scheduled to",
  GETEVENT_IMAGEURL: "http://localhost:3000/upload/getEvent/",
  FILE_IMAGE_URL: "http://localhost:3000/upload/getEvent/",
  IMAGE_FAILED_TO_SAVE: "The Image failed to save.",
  EVENT_CREATION_FAILED: "Event creation failed.",
  INVALID_DATE: "Invalid date. Must be in mm-dd-yy format",
  USER_NOT_FOUND: "User with this email not found.",
  NO_UPCOMING_EVENTS: "No upcoming events found.",
  REMINDER_SENT: "Reminder sent for event ID:",
  FAILED_TO_SENT_REMINDER: "Failed to send reminder for event ID",
  ERROR_HANDLE_REMINDER: "Error handling reminders:",
  SEATS_LEFT_MSG: "register fast! only 15 or less seats are left for ",
  REGISTER_FAST: "Register fast! only 15 or less seats are left",
};
