export const Messages = {
  USER: {
    CREATED: "User has been created successfully.",
    UPDATED: "User details updated successfully.",
    DELETED: "User deleted successfully.",
    NOT_FOUND: "User not found.",
    INVALID_USERID: "Invalid user ID",
  },
  AUTH: {
    LOGIN_SUCCESS: "Login successful.",
    LOGIN_FAILED: "Invalid credentials.",
    UNAUTHORIZED: "Unauthorized: Invalid token",
    EMAIL: "Email already exists.",
  },
  COMMON: {
    INTERNAL_SERVER_ERROR: "Something went wrong. Please try again later.",
  },
  URL: {
    imageUrl: "http://localhost:3000/upload/getProfile/",
    GETPROFILE_IMAGEURL: "http://localhost:3000/upload/getProfile/",
  },
  FILTER: "Only JPEG and PNG files are allowed",
  UPDATED_PROFILE: "Profile picture updated successfully",
  FILE_FORMAT: "Invalid file format. Please upload JPEG or PNG images only.",
  BASE64_FILENAME: "Base64 string and filename are required.",
  FILE_NOT_FOUND: "FIle not found",
  ERROR_To_SAVE_FILE: "Error saving file",

  INVALID_FILETYPE: "Invalid file upload. Please provide a valid file",
  IMAGE_FAILED_TO_SAVE: "The Image failed to save.",
  IMAGE_FAILED_TO_SAVE_IN_FOLDER: "The Image failed to save in folder.",
  UPLOAD_FILE_FAILED: "Uploading the file failed.",
  PROFILE_UPLOADED: "The profile is uploaded !",
  PROFILE_UPDATED: "The profile is updated !",
  SERVER_ERROR: "Internal server error",
  GET_PROFILE_WITH_FILENAME: "Get profile with filename",
  UPDATE_PROFILE_PIC: "Update profile picture",
  PROFILE_CREATED: "Profile picture created.",
  FILE_NOT_RECIEVED: "File not recieved.",
};
